name: "User Story Deutsch"
description: "Erstelle eine User Story"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Bitte fülle die folgenden Abschnitte aus, um die User Story zu beschreiben.

  - type: textarea
    id: rolle
    attributes:
      label: "Als (Rolle)"
      placeholder: "z.B., Als Kunde"
    validations:
      required: true
  
  - type: textarea
    id: ziel
    attributes:
      label: "Möchte ich (Ziel)"
      placeholder: "z.B., Möchte ich meine Bestellhistorie einsehen"
    validations:
      required: true
  
  - type: textarea
    id: grund
    attributes:
      label: "Damit (Grund)"
      placeholder: "z.B., Damit ich schnell wieder bestellte Produkte nachbestellen kann"
    validations:
      required: true

  - type: textarea
    id: beschreibung
    attributes:
      label: "Beschreibung"
      placeholder: "Gib eine detaillierte Beschreibung der User Story an"
    validations:
      required: true

  - type: textarea
    id: akzeptanzkriterien
    attributes:
      label: "Akzeptanzkriterien"
      placeholder: |
        - [ ] Akzeptanzkriterium 1
        - [ ] Akzeptanzkriterium 2
        - [ ] Akzeptanzkriterium 3
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Vielen Dank, dass du diese User Story erstellt hast! Wir werden sie überprüfen und uns bald bei dir melden.
