name: "User Story English"
description: "Create a user story"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to describe the user story.

  - type: textarea
    id: role
    attributes:
      label: "As a (role)"
      placeholder: "e.g., As a customer"
    validations:
      required: true
  
  - type: textarea
    id: goal
    attributes:
      label: "I want to (goal)"
      placeholder: "e.g., I want to view my order history"
    validations:
      required: true
  
  - type: textarea
    id: reason
    attributes:
      label: "So that (reason)"
      placeholder: "e.g., So that I can reorder quickly"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: "Provide a detailed description of the user story"
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      placeholder: |
        - [ ] Acceptance criterion 1
        - [ ] Acceptance criterion 2
        - [ ] Acceptance criterion 3
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thanks for creating this user story! We will review it and get back to you soon.
