name: Test comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
jobs:
  build:
    name: Test comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Pull Request is ready!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}